@BreakEven_HostAddress = http://localhost:8080

GET {{BreakEven_HostAddress}}/api/employee
Accept: application/json
###

GET {{BreakEven_HostAddress}}/api/employee/12345678910
Accept: application/json
###

POST {{BreakEven_HostAddress}}/api/employee
Accept: application/json
Content-Type: application/json

{
  "firstName": "Junior",
  "surName": "Teste",
  "cpf": "12345678910",
  "sector": "Management",
  "grossSalary": 20000,
  "admissionDate": "2023-11-29T15:02:23.408Z",
  "hasHealthInsurance": true,
  "hasDentalInsurance": true,
  "hasTransportationAllowance": true
}
###

GET {{BreakEven_HostAddress}}/api/employee/12345678910/paycheck
Accept: application/json
