// <auto-generated />
using System;
using BreakEven.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BreakEven.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231201180549_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BreakEven.API.Entities.Employee", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("GrossSalary")
                        .HasColumnType("double");

                    b.Property<bool>("HasDentalInsurance")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasHealthInsurance")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasTransportationAllowance")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CPF");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
